In [8]:
import pandas as pd
from collections import defaultdict, Counter

In [9]:
dir = "C:/Users/valer/Documents/CIC/doctorado/A24/Tesis/contingencias.csv"
df = pd.read_csv(dir, encoding = "Latin1")
df

,contaminante,zona,valor_activacion(ppb),estacion_inicio,dia_semana_inicio,fecha_activacion,hora_inicio,fase,valor_maximo,estacion_durante,fecha_durante,hora_durante,fecha_desactivacion,hora_levantamiento,valor_desactivacion_levantamiento,año
0,Ozono,CE/ SO / SO,158 / 157 / 155,Benito Juárez / Centro de Ciencias de la Atmó...,NaN,22/05/2024,14:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,Ozono,NO,177,Cuautitlán,NaN,13/05/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
2,Ozono,NO,113,Cuautitlán,NaN,30/04/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
3,Ozono,NO / NO / NO,162 / 161 / 155,Atizapán / Cuautitlán / Villa de las Flores,NaN,23/03/2024,16:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
4,Ozono,NO,163,Atizapán,NaN,22/02/2024,15:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Ozono,SO,340,Pedregal,Miércoles,23/10/1991,14:00,II,340,Pedregal,23/10/1991,13:00,33536,16:00,179,1991
88,Ozono,SO,267,Plateros,Miércoles,06/03/1991,12:00,I,315,ENEP Acatlán,07/03/1991,12:00,33307,14:00,162,1991
89,Ozono,CE,249,Merced,Sábado,02/02/1991,13:00,I,249,Merced,02/02/1991,13:00,33273,16:00,184,1991
90,Ozono,SO,298,PED/PLA,Jueves,25/02/1988,12:00,I,298,PED/PLA,25/02/1988,13:00,32201,12:00,196,1988
91,Ozono,SO,233,PED/PLA,Miércoles,03/02/1988,12:00,I,266,PED/PLA,04/02/1988,13:00,32178,12:00,142,1988

In [10]:
zonas_cont = []
estaciones_cont = []
for i in range(len(df)):
    zonas = df.iloc[i].zona
    zonas_lista = zonas.split('/')
    zonas_lista = [palabra.strip().upper() for palabra in zonas_lista]
    estaciones = df.iloc[i].estacion_inicio
    estaciones_lista = estaciones.split('/')
    estaciones_lista = [palabra.strip().upper() for palabra in estaciones_lista]
    if len(zonas_lista) == len(estaciones_lista):
        for j in range(len(zonas_lista)):
            zonas_cont.append(zonas_lista[j])
            estaciones_cont.append(estaciones_lista[j])

In [12]:
estaciones_cont = [s.replace('-', '').replace(' ', '') for s in estaciones_cont]
estaciones_cont = [s.replace('ENEPACATLÁN', 'FESACATLÁN') for s in estaciones_cont]

In [13]:
# Paso 1: Crear un diccionario para almacenar valores por categoría
valores_por_categoria = defaultdict(list)

# Paso 2: Recorrer ambas listas y agregar valores al diccionario según la categoría
for categoria, valor in zip(zonas_cont, estaciones_cont):
    valores_por_categoria[categoria].append(valor)

# Paso 3: Contar las ocurrencias de cada valor por categoría y encontrar el más común
resultados = {}

for categoria, lista_valores in valores_por_categoria.items():
    conteo = Counter(lista_valores)
    valor_mas_comun, cantidad = conteo.most_common(1)[0]
    resultados[categoria] = (valor_mas_comun, cantidad)

# Mostrar resultados
for categoria, (valor, cantidad) in resultados.items():
    print(f"Categoría {categoria}: Valor más común es {valor} con {cantidad} repeticiones.")

Categoría CE: Valor más común es BENITOJUÁREZ con 5 repeticiones.
Categoría SO: Valor más común es PEDREGAL con 22 repeticiones.
Categoría NO: Valor más común es FESACATLÁN con 8 repeticiones.
Categoría SE: Valor más común es SANTIAGOACAHUALTEPEC con 2 repeticiones.
Categoría NE: Valor más común es NEZAHUALCÓYOTL con 3 repeticiones.

In [17]:
# Contar las ocurrencias de cada valor en la lista
conteo = Counter(estaciones_cont)

# Obtener todos los valores y sus conteos, ordenados de mayor a menor frecuencia
valores_ordenados = conteo.most_common()

# Mostrar resultados
valor_mas_comun, cantidad = conteo.most_common(1)[0]
print(f"El valor más común es {valor_mas_comun} con {cantidad} repeticiones.")

# Mostrar resultados
print("Valores ordenados por frecuencia (de mayor a menor):")
for valor, cantidad in valores_ordenados:
    #print(f"Valor {valor}: {cantidad} repeticiones")
    print(valor, cantidad)

El valor más común es PEDREGAL con 22 repeticiones.
Valores ordenados por frecuencia (de mayor a menor):
PEDREGAL 22
PLATEROS 12
FESACATLÁN 8
CENTRODECIENCIASDELAATMÓSFERA 6
BENITOJUÁREZ 5
VILLADELASFLORES 4
AJUSCOMEDIO 4
SANTAFE 4
CUAUTITLÁN 3
NEZAHUALCÓYOTL 3
ATIZAPÁN 2
SANTIAGOACAHUALTEPEC 2
CUAJIMALPA 2
CAMARONES 2
SANAGUSTÍN 2
GUSTAVOA.MADERO 2
XALOSTOC 2
TLÁHUAC 2
AZCAPOTZALCO 2
TACUBA 2
TLALPAN 1
TULTITLÁN 1
MIGUELHIDALGO 1
AJUSCO 1
MERCED 1