In [2]:
import pandas as pd
from collections import defaultdict, Counter

In [2]:
dir = "C:/Users/valer/Documents/CIC/doctorado/A24/Tesis/contingencias.csv"
df = pd.read_csv(dir, encoding = "Latin1")
df

,contaminante,zona,valor_activacion(ppb),estacion_inicio,dia_semana_inicio,fecha_activacion,hora_inicio,fase,valor_maximo,estacion_durante,fecha_durante,hora_durante,fecha_desactivacion,hora_levantamiento,valor_desactivacion_levantamiento,año
0,Ozono,CE/ SO / SO,158 / 157 / 155,Benito Juárez / Centro de Ciencias de la Atmó...,NaN,22/05/2024,14:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,Ozono,NO,177,Cuautitlán,NaN,13/05/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
2,Ozono,NO,113,Cuautitlán,NaN,30/04/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
3,Ozono,NO / NO / NO,162 / 161 / 155,Atizapán / Cuautitlán / Villa de las Flores,NaN,23/03/2024,16:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
4,Ozono,NO,163,Atizapán,NaN,22/02/2024,15:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Ozono,SO,340,Pedregal,Miércoles,23/10/1991,14:00,II,340,Pedregal,23/10/1991,13:00,33536,16:00,179,1991
88,Ozono,SO,267,Plateros,Miércoles,06/03/1991,12:00,I,315,ENEP Acatlán,07/03/1991,12:00,33307,14:00,162,1991
89,Ozono,CE,249,Merced,Sábado,02/02/1991,13:00,I,249,Merced,02/02/1991,13:00,33273,16:00,184,1991
90,Ozono,SO,298,PED/PLA,Jueves,25/02/1988,12:00,I,298,PED/PLA,25/02/1988,13:00,32201,12:00,196,1988
91,Ozono,SO,233,PED/PLA,Miércoles,03/02/1988,12:00,I,266,PED/PLA,04/02/1988,13:00,32178,12:00,142,1988

In [3]:
zonas_cont = []
estaciones_cont = []
for i in range(len(df)):
    zonas = df.iloc[i].zona
    zonas_lista = zonas.split('/')
    zonas_lista = [palabra.strip().upper() for palabra in zonas_lista]
    estaciones = df.iloc[i].estacion_inicio
    estaciones_lista = estaciones.split('/')
    estaciones_lista = [palabra.strip().upper() for palabra in estaciones_lista]
    if len(zonas_lista) == len(estaciones_lista):
        for j in range(len(zonas_lista)):
            zonas_cont.append(zonas_lista[j])
            estaciones_cont.append(estaciones_lista[j])

In [4]:
estaciones_cont = [s.replace('-', '').replace(' ', '') for s in estaciones_cont]
estaciones_cont = [s.replace('ENEPACATLÁN', 'FESACATLÁN') for s in estaciones_cont]

In [5]:
# Paso 1: Crear un diccionario para almacenar valores por categoría
valores_por_categoria = defaultdict(list)

# Paso 2: Recorrer ambas listas y agregar valores al diccionario según la categoría
for categoria, valor in zip(zonas_cont, estaciones_cont):
    valores_por_categoria[categoria].append(valor)

# Paso 3: Contar las ocurrencias de cada valor por categoría y encontrar el más común
resultados = {}

for categoria, lista_valores in valores_por_categoria.items():
    conteo = Counter(lista_valores)
    valor_mas_comun, cantidad = conteo.most_common(1)[0]
    resultados[categoria] = (valor_mas_comun, cantidad)

# Mostrar resultados
for categoria, (valor, cantidad) in resultados.items():
    print(f"Categoría {categoria}: Valor más común es {valor} con {cantidad} repeticiones.")

Categoría CE: Valor más común es BENITOJUÁREZ con 5 repeticiones.
Categoría SO: Valor más común es PEDREGAL con 22 repeticiones.
Categoría NO: Valor más común es FESACATLÁN con 8 repeticiones.
Categoría SE: Valor más común es SANTIAGOACAHUALTEPEC con 2 repeticiones.
Categoría NE: Valor más común es NEZAHUALCÓYOTL con 3 repeticiones.

In [73]:
dir = "C:/Users/valer/Documents/CIC/doctorado/A24/Tesis/EstacionesContingencia.csv"
key_estaciones = pd.read_csv(dir, encoding = "Latin1")
key_estaciones["Nombre"] = key_estaciones["Nombre"].str.lower()
lista = []
for i in range(len(key_estaciones)):
    a = key_estaciones["Nombre"].iloc[i]
    a = a.lower()
    a = a.replace('-', '').replace(' ', '')
    lista.append(a)
key_estaciones["Nombre"] = lista
key_estaciones.head()

,Clave,Nombre,Alcaldía o municipio,Entidad,Monitorea_Contingencia,Ya_activó_contingencias,objetivo05RAMA
0,ACO,acolman,Acolman,Estado de México,0,No activa contingencias,NaN
1,AJM,ajusco medio,Tlalpan,CDMX,1,Ya_activó,Si
2,AJU,ajusco,Tlalpan,CDMX,0,Ya_activó,NaN
3,ATI,atizapán,Atizapán de Zaragoza,Estado de México,1,NaN,Si
4,BJU,benito juarez,Benito Juárez,CDMX,1,Ya_activó,Si

In [ ]:
estaciones_dict = {
'CE' : {'Alcaldias': ['Benito Juárez', 'Cuauhtémoc', 'Iztacalco', 'Venustiano Carranza']},
'NE' : {'Alcaldias': ['Gustavo A. Madero'],
      'Municipios':  ['Acolman', 'Atenco', 'Axapusco', 'Chiautla', 'Chicoloapan', 'Chiconcuac', 'Chimalhuacán', 'Coacalco de Berriozábal','Ecatepec de Morelos', 'Hueypoxtla', 'Ixtapaluca', 'Jaltenco', 'La Paz', 'Nextlalpan', 'Nezahualcóyotl', 'Nopaltepec', 'Otumba', 'Papalotla', 'San Martín de las Pirámides', 'Tecámac', 'Temascalapa', 'Teotihuacán', 'Tepetlaoxtoc', 'Texcoco', 'Tezoyuca', 'Tonanitla', 'Zumpango']},
'NO' : {'Alcaldias': ['Azcapotzalco', 'Miguel Hidalgo'],
      'Municipios':  ['Apaxco', 'Atizapán de Zaragoza', 'Coyotepec', 'Cuautitlán', 'Cuautitlán Izcalli', 'Huehuetoca', 'Isidro Fabela', 'Jilotzingo', 'Melchor Ocampo', 'Naucalpan de Juárez', 'Nicolás Romero', 'Teoloyucan', 'Tepotzotlán', 'Tequixquiac', 'Tlalnepantla de Baz', 'Tultepec', 'Tultitlán', 'Villa del Carbón']},
'SE' : {'Alcaldias': ['Iztapalapa', 'Milpa Alta', 'Tláhuac', 'Xochimilco'],
      'Municipios':  ['Amecameca', 'Atlautla', 'Ayapango', 'Chalco', 'Cocotitlán', 'Ecatzingo', 'Juchitepec', 'Ozumba', 'Temamatla', 'Tenango del Aire', 'Tepetlixpa', 'Tlalmanalco', 'Valle de Chalco Solidaridad']},
'SO' : {'Alcaldias': ['Álvaro Obregón', 'Coyoacán', 'Cuajimalpa de Morelos', 'La Magdalena Contreras', 'Tlalpan'], 
      'Municipios': ['Huixquilucan', 'Ocoyoacac']}
}

In [83]:
# Contar las ocurrencias de cada valor en la lista
conteo = Counter(estaciones_cont)

# Obtener todos los valores y sus conteos, ordenados de mayor a menor frecuencia
valores_ordenados = conteo.most_common()

# Mostrar resultados
valor_mas_comun, cantidad = conteo.most_common(1)[0]
print(f"El valor más común es {valor_mas_comun} con {cantidad} repeticiones.")

# Mostrar resultados
print("Valores ordenados por frecuencia (de mayor a menor):")
zonas_mayor_contingencia = []
for valor, cantidad in valores_ordenados:
    #print(f"Valor {valor}: {cantidad} repeticiones")
    station_name = valor.lower()
    station_name = valor.lower()
    row = key_estaciones[key_estaciones["Nombre"]==station_name]
    if len(row) == 0:
        print(valor, cantidad)
    else:
        for zona in estaciones_dict:
            for nivel2 in estaciones_dict[zona]:
                for lugar in estaciones_dict[zona][nivel2]:
                    if row["Alcaldía o municipio"].iloc[0] == lugar:
                        print(zona, valor, cantidad)
                        for ca in range(cantidad):
                            zonas_mayor_contingencia.append(zona)

El valor más común es PEDREGAL con 22 repeticiones.
Valores ordenados por frecuencia (de mayor a menor):
SO PEDREGAL 22
PLATEROS 12
NO FESACATLÁN 8
SO CENTRODECIENCIASDELAATMÓSFERA 6
BENITOJUÁREZ 5
NE VILLADELASFLORES 4
SO AJUSCOMEDIO 4
SO SANTAFE 4
NO CUAUTITLÁN 3
NE NEZAHUALCÓYOTL 3
NO ATIZAPÁN 2
SE SANTIAGOACAHUALTEPEC 2
SO CUAJIMALPA 2
NO CAMARONES 2
NE SANAGUSTÍN 2
NE GUSTAVOA.MADERO 2
NE XALOSTOC 2
SE TLÁHUAC 2
AZCAPOTZALCO 2
TACUBA 2
TLALPAN 1
NO TULTITLÁN 1
NO MIGUELHIDALGO 1
SO AJUSCO 1
CE MERCED 1

In [84]:
conteo = Counter(zonas_mayor_contingencia)
conteo

Counter({'SO': 39, 'NO': 17, 'NE': 13, 'SE': 4, 'CE': 1})

# Conteo otro

### Cálculo del número de contingenicas ambientales activadas por cada estación , en cada zona

In [3]:
dir = "C:/Users/valer/Documents/CIC/doctorado/A24/Tesis/contingencias.csv"
contingencias = pd.read_csv(dir, encoding="Latin1")
contingencias

,contaminante,zona,valor_activacion(ppb),estacion_inicio,dia_semana_inicio,fecha_activacion,hora_inicio,fase,valor_maximo,estacion_durante,fecha_durante,hora_durante,fecha_desactivacion,hora_levantamiento,valor_desactivacion_levantamiento,año
0,Ozono,CE/ SO / SO,158 / 157 / 155,Benito Juárez / Centro de Ciencias de la Atmó...,NaN,22/05/2024,14:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,Ozono,NO,177,Cuautitlán,NaN,13/05/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
2,Ozono,NO,113,Cuautitlán,NaN,30/04/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
3,Ozono,NO / NO / NO,162 / 161 / 155,Atizapán / Cuautitlán / Villa de las Flores,NaN,23/03/2024,16:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
4,Ozono,NO,163,Atizapán,NaN,22/02/2024,15:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Ozono,SO,340,Pedregal,Miércoles,23/10/1991,14:00,II,340,Pedregal,23/10/1991,13:00,33536,16:00,179,1991
88,Ozono,SO,267,Plateros,Miércoles,06/03/1991,12:00,I,315,ENEP Acatlán,07/03/1991,12:00,33307,14:00,162,1991
89,Ozono,CE,249,Merced,Sábado,02/02/1991,13:00,I,249,Merced,02/02/1991,13:00,33273,16:00,184,1991
90,Ozono,SO,298,PED/PLA,Jueves,25/02/1988,12:00,I,298,PED/PLA,25/02/1988,13:00,32201,12:00,196,1988
91,Ozono,SO,233,PED/PLA,Miércoles,03/02/1988,12:00,I,266,PED/PLA,04/02/1988,13:00,32178,12:00,142,1988

In [4]:
contingencias.zona.unique()

array(['CE/ SO / SO', 'NO', 'NO / NO / NO', 'SO / SO', 'SO', 'SE', 'CE',
       'CE / SO', 'NE'], dtype=object)

In [5]:
zonaNO = contingencias[contingencias.zona=="NO"]
print(len(zonaNO))
estacionesCONcontingencia = zonaNO['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaNO:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

18
El valor más repetido en zonaNO: ENEP Acatlán
La frecuencia del valor más repetido es: 7

In [6]:
zonaSO = contingencias[contingencias.zona=="SO"]
print(len(zonaSO))
estacionesCONcontingencia = zonaSO['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaSO:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

50
El valor más repetido en zonaSO: Pedregal
La frecuencia del valor más repetido es: 21

In [7]:
zonaSE = contingencias[contingencias.zona=="SE"]
print(len(zonaSE))
estacionesCONcontingencia = zonaSE['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaSE:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

4
El valor más repetido en zonaSE: Santiago Acahualtepec
La frecuencia del valor más repetido es: 2

In [8]:
zonaCE = contingencias[contingencias.zona=="CE"]
print(len(zonaCE))
estacionesCONcontingencia = zonaCE['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaCE:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

4
El valor más repetido en zonaCE: Benito Juárez
La frecuencia del valor más repetido es: 3

In [9]:
zonaNE = contingencias[contingencias.zona=="NE"]
print(len(zonaNE))
estacionesCONcontingencia = zonaNE['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaNE:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

12
El valor más repetido en zonaNE: Nezahualcóyotl
La frecuencia del valor más repetido es: 3

In [10]:
zonaCESO = contingencias[contingencias.zona=="CE / SO"]
print(len(zonaCESO))
estacionesCONcontingencia = zonaCESO['estacion_inicio'].value_counts()

# Encuentra el valor más repetido y su frecuencia
valor_mas_repetido = estacionesCONcontingencia.idxmax()  # Obtiene el índice (el valor en sí)
frecuencia_maxima = estacionesCONcontingencia.max()      # Obtiene la frecuencia máxima

print("El valor más repetido en zonaCESO:", valor_mas_repetido)
print("La frecuencia del valor más repetido es:", frecuencia_maxima)

1
El valor más repetido en zonaCESO: Benito Juárez / Centro de Ciencias de la Atmósfera
La frecuencia del valor más repetido es: 1

In [11]:
len(contingencias)

92