In [1]:
import pandas as pd

In [5]:
dir = "C:/Users/valer/Documents/CIC/doctorado/A24/Tesis/contingencias.csv"
df = pd.read_csv(dir, encoding = "Latin1")
df

,contaminante,zona,valor_activacion(ppb),estacion_inicio,dia_semana_inicio,fecha_activacion,hora_inicio,fase,valor_maximo,estacion_durante,fecha_durante,hora_durante,fecha_desactivacion,hora_levantamiento,valor_desactivacion_levantamiento,año
0,Ozono,CE/ SO / SO,158 / 157 / 155,Benito Juárez (BJU) / Centro de Ciencias de la...,NaN,22/05/2024,14:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,Ozono,NO,177,Cuautitlán,NaN,13/05/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
2,Ozono,NO,113,Cuautitlán,NaN,30/04/2024,17:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
3,Ozono,NO / NO / NO,162 / 161 / 155,Atizapán / Cuautitlán / Villa de las Flores,NaN,23/03/2024,16:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
4,Ozono,NO,163,Atizapán,NaN,22/02/2024,15:00,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Ozono,SO,340,Pedregal,Miércoles,23/10/1991,14:00,II,340,Pedregal,23/10/1991,13:00,33536,16:00,179,1991
88,Ozono,SO,267,Plateros,Miércoles,06/03/1991,12:00,I,315,ENEP Acatlán,07/03/1991,12:00,33307,14:00,162,1991
89,Ozono,CE,249,Merced,Sábado,02/02/1991,13:00,I,249,Merced,02/02/1991,13:00,33273,16:00,184,1991
90,Ozono,SO,298,PED/PLA,Jueves,25/02/1988,12:00,I,298,PED/PLA,25/02/1988,13:00,32201,12:00,196,1988
91,Ozono,SO,233,PED/PLA,Miércoles,03/02/1988,12:00,I,266,PED/PLA,04/02/1988,13:00,32178,12:00,142,1988

In [8]:
i=1
zonas = df.iloc[i].zona
palabras = zonas.split('/')
palabras_limpias = [palabra.strip().upper() for palabra in palabras]
palabras_limpias

['NO']

In [ ]:
palabras = mi_string.split('/')

# Paso 2: Eliminar los espacios adicionales y convertir a mayúsculas
palabras_limpias = [palabra.strip().upper() for palabra in palabras]

In [ ]:
for i in range(len(df)):
    zonas = df.iloc[i].zona
    zonas_lista = zonas.split('/')
    zonas_lista = [palabra.strip().upper() for palabra in zonas_lista]
    estaciones = df.iloc[i].estacion_inicio
    estaciones_lista = zonas.split('/')
    estaciones_lista = [palabra.strip().upper() for palabra in estaciones_lista]
    for zona in zonas_lista: